{
 "title": "Triton Inference Server",
 "description": "Nvidia Triton inference server metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mean Inference Time (Microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us{model=\"simple\"} / nv_inference_count{model=\"simple\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Inference Success/Failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nv_inference_request_success{model=\"simple\"}",
     "legendFormat": "Success {{instance}}"
    },
    {
     "expr": "nv_inference_request_failure{model=\"simple\"}",
     "legendFormat": "Failure {{instance}}"
    }
   ]
  },
  {
   "title": "Mean Inference Rate (Microseconds/Inference)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us{model=\"simple\"} / nv_inference_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Queue Duration (Microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "nv_inference_queue_duration_us{model=\"simple\"} / nv_inference_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Inference Compute Time (Microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_duration_us{model=\"simple\"} / nv_inference_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}